// games-react-couchdb/src/App.js
import React, { Component } from 'react'
import { BrowserRouter, Switch, Route, Link } from 'react-router-dom'
import ListGames from './games/ListGames'
import './App.css'
import AddGame from './games/AddGame'
import SearchGame from './games/SearchGame'
import DeleteGame from './games/DeleteGame'
import EditGame from './games/EditGame'
class App extends Component {

  render() {
    return (
        <div id="app" className = 'container'>
          <header>
          <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="/">Game App</a>
            <button id="hamburgerBtn" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                 <a id="test" class="nav-link" href="/">List</a>
              </li>
              <li class="nav-item">
                 <a id="navAdd" class="nav-link" href="/add">Add</a>
              </li>
              <li class="nav-item">
                 <a id="navSearch" class="nav-link" href="/search">Search</a>
              </li>
              <li class="nav-item">
                 <a id="navDelete" class="nav-link" href="/delete">Delete</a>
              </li>
            </ul>
          </div>
          </nav>
          </header>
        <BrowserRouter>
            <Switch>
              <Route exact path='/list'><ListGames/></Route>
              <Route exact path='/search'><SearchGame/></Route>
              <Route path='/delete/:game' component={ DeleteGame } />
              <Route path='/delete'><DeleteGame/></Route>
              <Route path='/edit/:game' component={ EditGame }/>
              <Route path='/add'><AddGame/></Route>
              <Route path='*'><ListGames/></Route>
            </Switch>  
        </BrowserRouter>
        </div> 
      )
    }
  }
  
  export default App

// games-angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'games-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'games-angular';
  author = '';
  names = ['Robin','Dirk','Paljas','Gregory','Karolien'];

  ngOnInit(): void {
    var randomNumber  = Math.floor(Math.random() * this.names.length);
    console.log(randomNumber)
    this.author = this.names[randomNumber];
  }
}

<div class='container'>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="">Game App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" [routerLink]="['']">List</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" [routerLink]="['add']">Add</a>
        </li>
      </ul>
    </div>
  </nav>
  <br/><br/>
  <router-outlet></router-outlet>
  <a>Brought to you by <b>{{author}}</b></a>
</div>
